- hosts: openstack
  user: root
  roles:
    - prepare_host 

- hosts: openstack
  user: root 
  tasks:
    - name: Open Geneve UDP port for tunneling
      command: iptables -I INPUT -m state --state NEW -p udp --dport 6081 -j ACCEPT
    - name: Persist iptables changes after a reboot
      shell: iptables-save > /etc/sysconfig/iptables.save

- hosts: controller_hosts
  user: root
  roles:
    - ovn_northd

- hosts: compute_hosts:network_hosts
  user: root
  roles:
    - ovn_controller

- hosts: controller_hosts
  user: root
  tasks:
    - name: Restart Neutron Server
      command: docker start "{{ item }}"
      with_items:
        - neutron_server

#- hosts: network_hosts
#  user: root
#  tasks:
#    - name: Restart L3 Agent
#      command: docker start "{{ item }}"
#      with_items:
#        - neutron_l3_agent

- hosts: ovndb_hosts
  user: root
  tasks:
    - name: Sync Neutron state to OVN
      command: "docker exec neutron_server {{ item }}"
      with_items:
        - neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade heads
        - neutron-ovn-db-sync-util --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini

