- name: Pull ovn_controller
  command: docker pull {{ docker_registry }}/ovn-controller

- name: Check ovn-controller is running
  command: docker ps
  register: ovn_controller_run

- name: start ovn-controller
  command: docker run -d --privileged --net=host --name ovn-controller -v "/etc/localtime:/etc/localtime:ro"  -v "/run:/run:shared" -v "/lib/modules:/lib/modules:ro" -v /var/log/openvswitch:/var/log/openvswitch {{ docker_registry }}/ovn-controller
  when: ovn_controller_run.stdout.find('ovn-controller') == -1


- name: Install L3 agent configuration
  ini_file: dest={{ item.dest }} section={{ item.section }} option={{ item.option }} value={{ item.value }}
  with_items:
      - { dest: '/etc/kolla/neutron-l3-agent/l3_agent.ini', section: 'DEFAULT', option: 'interface_driver', value: 'openvswitch' }
      - { dest: '/etc/kolla/neutron-l3-agent/l3_agent.ini', section: 'DEFAULT', option: 'ovs_use_veth', value: 'False' }
      - { dest: '/etc/kolla/neutron-l3-agent/l3_agent.ini', section: 'DEFAULT', option: 'debug', value: 'True' }
      - { dest: '/etc/kolla/neutron-l3-agent/l3_agent.ini', section: 'DEFAULT', option: 'external_network_bridge', value: '' }
      - { dest: '/etc/kolla/neutron-l3-agent/l3_agent.ini', section: 'AGENT', option: 'root_helper_daemon', value: 'sudo /usr/bin/neutron-rootwrap-daemon /etc/neutron/rootwrap.conf' }
      - { dest: '/etc/kolla/neutron-l3-agent/l3_agent.ini', section: 'AGENT', option: 'root_helper', value: 'sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf' }
  when: inventory_hostname in groups['network_hosts']



- name: Configure ovn-remote
  command: "docker exec ovn-controller ovs-vsctl set open . external_ids:ovn-remote=tcp:{{ ovn_db_ip }}:{{ ovn_southbound_port }}"
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 5

- name: Configure system-id
  command: "docker exec ovn-controller ovs-vsctl set open . external-ids:system-id={{ hostname }}"

- name: Configure ovn-encap-type
  command: "docker exec ovn-controller ovs-vsctl set open . external_ids:ovn-encap-type=geneve,vxlan"

- name: Configure ovn-encap-ip
  command: "docker exec ovn-controller ovs-vsctl set open . external_ids:ovn-encap-ip={{ ovn_node_ip }}"

- name: Set hostname
  command: "docker exec ovn-controller ovs-vsctl set Open_vSwitch . external-ids:hostname={{ hostname }}"

- name: Add {{ ovn_bridge_mappings }}
  command: "docker exec ovn-controller ovs-vsctl add-br {{ ovn_ex_bridge }}"
  when: inventory_hostname in groups['network_hosts']
  ignore_errors: True

- name: Configure ovn-bridge-mappings
  command: "docker exec ovn-controller ovs-vsctl set open . external_ids:ovn-bridge-mappings={{ ovn_bridge_mappings }}"
  when: inventory_hostname in groups['network_hosts']


- name: Add ovsdb-listen local ip for Ocata L3 agent
  command: "docker exec ovn-controller ovs-appctl -t ovsdb-server ovsdb-server/add-remote ptcp:6640:127.0.0.1"
  ignore_errors: True


