- name: Delete br-tun, br-ex, br-int
  command: "docker exec openvswitch_vswitchd ovs-vsctl del-br {{ item }}"
  with_items:
    - "br-ex"
    - "br-int"
    - "br-tun"
  ignore_errors: True

- name: Stop and disable metadata, DHCP, and openvswitch agents
  command: docker stop {{ item }}
  with_items:
      - "neutron_metadata_agent"
      - "neutron_dhcp_agent"
      - "neutron_openvswitch_agent"
  ignore_errors: True

- name: stop openvswitch services
  command: docker stop openvswitch_vswitchd
  ignore_errors: True

- name: stop openvswitch db
  command: docker stop openvswitch_db
  ignore_errors: True

- name: clear all items in openvswitch folder
  command: rm -rf /var/run/openvswitch
  ignore_errors: True

- name: Create openvsitch used folder
  command: mkdir -p /var/run/openvswitch
  ignore_errors: True
