- name: stop openvswitch services
  command: docker stop openvswitch_vswitchd
#  docker:
#    name: openvswitch_vswitchd
#    image: 192.168.200.87:5000/kolla/centos-binary-neutron-openvswitch-agent
#    state: stopped

- name: stop openvswitch db
  command: docker stop openvswitch_db
#  docker:
#    name: openvswitch_db
#    image: 192.168.200.87:5000/kolla/centos-binary-neutron-openvswitch-agent
#    state: stopped

- name: stop openvswitch agent
  command: docker stop neutron_openvswitch_agent
#  docker:
#    name: neutron_openvswitch_agent
#    image: 192.168.200.87:5000/kolla/centos-binary-neutron-openvswitch-agent
#    state: stopped

- name: Create openvsitch used folder
  command: mkdir -p /var/run/openvswitch


