- name: Launch ovn-northd
  command: docker-compose -f /root/ovn_northd_compose.yml up -d

- name: Open OVN database ports
  command: "iptables -I INPUT -m state --state NEW -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - "{{ ovn_northbound_port }}"
    - "{{ ovn_southbound_port }}"

- name: Persist iptables changes after a reboot
  shell: iptables-save > /etc/sysconfig/iptables.save

- name: Enable remote access to northbound & southbound database
  command: "docker exec ovn-northd {{ item }}"
  with_items:
    - ovn-nbctl set-connection ptcp:{{ ovn_northbound_port }}:{{ ovn_db_ip }}
    - ovn-sbctl set-connection ptcp:{{ ovn_southbound_port }}:{{ ovn_db_ip }}

- name: Update Neutron configuration files
  ini_file: dest={{ item.dest }} section={{ item.section }} option={{ item.option }} value={{ item.value }}
  with_items:
      - { dest: '/etc/neutron/neutron.conf', section: 'DEFAULT', option: 'service_plugins', value: 'qos,neutron.services.l3_router.l3_router_plugin.L3RouterPlugin' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ml2', option: 'mechanism_drivers', value: 'ovn,logger' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ml2', option: 'type_drivers', value: 'local,flat,vlan,geneve' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ml2', option: 'tenant_network_types', value: 'geneve' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ml2', option: 'extension_drivers', value: 'port_security,qos' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ml2', option: 'overlay_ip_version', value: '4' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ml2_type_geneve', option: 'vni_ranges', value: '1:65536' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ml2_type_geneve', option: 'max_header_size', value: '38' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ml2_type_vlan', option: 'network_vlan_ranges', value: 'public' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'securitygroup', option: 'enable_security_group', value: 'True' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ovn', option: 'ovn_nb_connection', value: 'tcp:{{ ovn_db_ip }}:{{ ovn_northbound_port }}' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ovn', option: 'ovn_sb_connection', value: 'tcp:{{ ovn_db_ip }}:{{ ovn_southbound_port }}' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ovn', option: 'neutron_sync_mode', value: 'log' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ovn', option: 'ovn_l3_mode', value: 'False' }
      - { dest: '/etc/neutron/plugins/ml2/ml2_conf.ini', section: 'ovn', option: 'ovn_native_dhcp', value: 'True' }
      - { dest: '/etc/neutron/l3_agent.ini', section: 'DEFAULT', option: 'interface_driver', value: 'openvswitch' }


- name: Stop neutron-server to begin data sync to OVN
  systemd:
    name: neutron-server
    state: stopped

- name: Sync Neutron state to OVN
  when: ovn_central is defined
  command: "{{ item }}"
  with_items:
    - neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade heads
    - neutron-ovn-db-sync-util --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini
