- name: pull ovn-northd
  command: docker pull {{ docker_registry }}/ovn-northd
  when: inventory_hostname in groups['ovndb_hosts']

- name: check ovn-northd is running
  command: docker ps -a
  register: run_ovn_northd
  when: inventory_hostname in groups['ovndb_hosts']

- name: launch ovn-northd
  command: docker run -d --privileged --net=host --name ovn-northd -v "/etc/localtime:/etc/localtime:ro"  -v "/run:/run:shared" -v "/lib/modules:/lib/modules:ro" -v /var/log/openvswitch:/var/log/openvswitch {{ docker_registry }}/ovn-northd 
  when: (inventory_hostname in groups['ovndb_hosts']) and (run_ovn_northd.stdout.find('ovn-northd')==-1)

- name: restart ovn-northd
  command: docker restart ovn-northd
  when: (inventory_hostname in groups['ovndb_hosts']) and (run_ovn_northd.stdout.find('ovn-northd')!=-1)

- name: Open OVN database ports
  command: "iptables -I INPUT -m state --state NEW -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - "{{ ovn_northbound_port }}"
    - "{{ ovn_southbound_port }}"
  when: inventory_hostname in groups['ovndb_hosts']

- name: Persist iptables changes after a reboot
  shell: iptables-save > /etc/sysconfig/iptables.save
  when: inventory_hostname in groups['ovndb_hosts']

- name: Enable remote access to northbound & southbound database
  command: "docker exec ovn-northd {{ item }}"
  with_items:
    - ovn-nbctl set-connection ptcp:{{ ovn_northbound_port }}:{{ ovn_db_ip }}
    - ovn-sbctl set-connection ptcp:{{ ovn_southbound_port }}:{{ ovn_db_ip }}
  when: inventory_hostname in groups['ovndb_hosts']

- name: Update Neutron configuration files
  ini_file: dest={{ item.dest }} section={{ item.section }} option={{ item.option }} value={{ item.value }}
  with_items:
      - { dest: '/etc/neutron/neutron.conf', section: 'DEFAULT', option: 'service_plugins', value: 'qos,neutron.services.l3_router.l3_router_plugin.L3RouterPlugin' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ml2', option: 'mechanism_drivers', value: 'ovn,logger' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ml2', option: 'type_drivers', value: 'local,flat,vlan,geneve' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ml2', option: 'tenant_network_types', value: 'geneve' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ml2', option: 'extension_drivers', value: 'port_security,qos' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ml2', option: 'overlay_ip_version', value: '4' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ml2_type_geneve', option: 'vni_ranges', value: '1:65536' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ml2_type_geneve', option: 'max_header_size', value: '38' }
      - { dest: '/etc/kolla/neutron-server/ml2/ml2_conf.ini', section: 'ml2_type_vlan', option: 'network_vlan_ranges', value: 'public' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'securitygroup', option: 'enable_security_group', value: 'True' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ovn', option: 'ovn_nb_connection', value: 'tcp:{{ ovn_db_ip }}:{{ ovn_northbound_port }}' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ovn', option: 'ovn_sb_connection', value: 'tcp:{{ ovn_db_ip }}:{{ ovn_southbound_port }}' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ovn', option: 'neutron_sync_mode', value: 'log' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ovn', option: 'ovn_l3_mode', value: 'False' }
      - { dest: '/etc/kolla/neutron-server/ml2_conf.ini', section: 'ovn', option: 'ovn_native_dhcp', value: 'True' }
      - { dest: '/etc/kolla/neutron-l3-agent/l3_agent.ini', section: 'DEFAULT', option: 'interface_driver', value: 'openvswitch' }


- name: Stop neutron-server to begin data sync to OVN
  command: docker stop neutron_server

